apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel-app
spec:
  replicas: 3  # Set the number of desired replicas
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-app
          image: ermiasdev/todo:latest  # Use your Docker image
          ports:
            - containerPort: 80  # Port your Laravel app listens on
          env:
            - name: DB_HOST
              value: mysql  # MySQL hostname or IP
            - name: DB_DATABASE
              value: todo  # Database name
            - name: DB_USERNAME
              value: root  # Database username
            - name: DB_PASSWORD
              value:   # Database password
