apiVersion: v1
kind: Service
metadata:
  name: laravel-app-service
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80  # Port to expose
      targetPort: 80  # Port to forward traffic to
  type: LoadBalancer  # Use 'LoadBalancer' for external access, or 'ClusterIP' for internal access
